# Generated by Django 5.0.2 on 2024-02-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_news',
            name='preview',
            field=models.ImageField(upload_to='blog_previews/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
