# Generated by Django 5.0.2 on 2024-03-05 09:56

import blog.models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('blog', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('preview', models.ImageField(blank=True, upload_to=blog.models.user_directory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AlterField(
            model_name='subsection',
            name='blog_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='blog.news'),
        ),
        migrations.DeleteModel(
            name='BLOGG',
        ),
    ]
