# Generated by Django 5.0.2 on 2024-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_count_viewing'),
        ('profil', '0002_alter_profil_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='count_viewing',
            field=models.ManyToManyField(null=True, related_name='view_count', to='profil.profil'),
        ),
    ]
