# Generated by Django 5.0.2 on 2024-03-05 12:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_alter_subsection_blog_news_delete_blogg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_directory_path),
        ),
    ]
