# Generated by Django 5.0.2 on 2024-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_news_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_news',
            options={'ordering': ['-publish']},
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='preview',
            field=models.ImageField(upload_to='blog_previews/'),
        ),
    ]
