# Generated by Django 5.0.2 on 2024-03-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_news_options_alter_blog_news_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='subsection_images/')),
                ('blog_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='blog.blog_news')),
            ],
        ),
    ]
