# Generated by Django 5.0.2 on 2024-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
