# Generated by Django 5.0.2 on 2024-03-12 13:03

import django.db.models.deletion
import profil.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_username', models.GenericIPAddressField(blank=True, null=True)),
                ('user_photo', models.ImageField(blank=True, upload_to=profil.models.user_directory_path)),
                ('user_fon', models.ImageField(blank=True, upload_to=profil.models.user_directory_path)),
                ('user_about', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
